apiVersion: v1
kind: Service
metadata:
  name: add-service
  labels:
    name: phonebook-add
    app: add-api
spec:
  selector:
    name: phonebook-add
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001