apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: phonebook-db
    app: phonebook
spec:
  selector:
    name: phonebook-db
  type: ClusterIP
  ports:
    - name: db
      port: 3306
      targetPort: 3306