apiVersion: v1
kind: Service
metadata:
  name: search-service
  labels:
    name: phonebook-search
    app: search-api
spec:
  selector:
    name: phonebook-search
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002